version: '3.8'
services:
  db:
    image: postgres:12.4
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgressql/data
  frontend:
    image: nikismol94/frontend:v2.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  backend:
    image: nikismol94/backend:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./templates/default.conf.template:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - media_value:/media/
      - result_build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs
    restart: always
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  result_build:
  static_value:
  media_value:
